config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root "homes#index"
  get "admin_show/:id", to: "admins#show", as: :admin_show

  devise_scope :user do
    get "/admin_login", to: "users/sessions#new"
    get "/otp_verification", to: "users/confirmations#otp_verification", as: :verify
    patch "/verification", to: "users/sessions#otp_verification", as: :verify_login
    patch "/resend_otp", to: "users/sessions#resend_otp", as: :resend_otp
  end

  devise_scope :bus_owner do
    get "/otp_verification/busowner", to: "bus_owners/confirmations#otp_verification", as: :verify_busowner
    patch "/verification/busowner", to: "bus_owners/sessions#otp_verification", as: :verify_login_busowner
    patch "/resend_otp/busowner", to: "bus_owners/sessions#resend_otp", as: :resend_otp_busowner
  end

  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                       passwords: "users/passwords",
                       confirmations: "users/confirmations",
                     }

  devise_for :bus_owners, class_name: "User", controllers: {
                            registrations: "bus_owners/registrations",
                            sessions: "bus_owners/sessions",
                            passwords: "bus_owners/passwords",
                            confirmations: "bus_owners/confirmations",
                          }

  resources :users, only: [:show, :index]

  resources :bus_owners do
    resources :buses
  end

  resources :buses do
    resources :reservations, only: [:new, :create, :index, :destroy]
  end

  get "/searched_bus", to: "homes#search", as: :search
  get "/bookings/:user_id", to: "reservations#booking", as: :bookings
  get "/get_resv_list/:bus_id", to: "buses#reservations_list", as: :get_resv_list
  patch "approve/:bus_owner_id/:id", to: "admins#approve", as: :approve
  patch "disapprove/:bus_owner_id/:id", to: "admins#disapprove", as: :disapprove

  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/models/bus_owner.rb
class BusOwner < User
  has_many :buses, class_name: "Bus", foreign_key: "bus_owner_id", dependent: :destroy
  validates :registration_no, presence: true, uniqueness: true
  default_scope { where(user_type: User.user_types["bus_owner"]) }
end

app/controllers/bus_owners/confirmations_controller.rb
# frozen_string_literal: true

class BusOwners::ConfirmationsController < Devise::ConfirmationsController

  def otp_verification
    @token = params[:confirmation_token]
    @user = BusOwner.find_by(confirmation_token: @token)
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    params[:confirmation_token] = params[:bus_owner][:confirmation_token]
    @token = params[:confirmation_token]
    @user = BusOwner.find_by(confirmation_token: @token)
    if @user&.valid_otp?(params[:bus_owner][:otp])
      super
    else
      flash.now[:alert] = 'Invalid OTP'
      render :otp_verification, status: :unprocessable_entity
    end
  end

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/bus_owners/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class BusOwners::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/bus_owners/passwords_controller.rb
# frozen_string_literal: true

class BusOwners::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/bus_owners/registrations_controller.rb
class BusOwners::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  def new 
    @type = "bus_owner" #needed in views to determine user_type
    super
  end
 
  def after_sign_up_path_for(resource)
    bus_owner_path(resource)
  end
  
  def after_update_path_for(resource)
    bus_owner_path(resource) 
  end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :registration_no, :user_type ])
    params[:bus_owner][:user_type] = 'bus_owner'
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :registration_no])
  end
end

app/controllers/bus_owners/sessions_controller.rb
class BusOwners::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  def new
    super
  end
    
  def otp_verification
    sign_out(current_user) if current_user
    @email = params[:email] 
    @user = BusOwner.find_by(email: @email)
    @remember_me = params[:remember_me] 
    if ( ( @user && @user.valid_password?( params[:password] ) ) && @user&.confirmed? )
      @user.generate_and_send_otp
      flash.now[:notice] = 'A new OTP has been sent to your email.'
      respond_to do |format|
        format.html {render :otp_verification}
        format.turbo_stream { render turbo_stream: turbo_stream.update("otp", partial: 
        "bus_owners/sessions/otp_verification", locals: {email: @email, remember_me: @remember_me})}
      end
    else 
      if @user 
        if @user.confirmed?
          flash.now[:alert] = 'Invalid  password!'
        else
          flash.now[:alert] = 'You have to confirm your email first!'   
        end 
      else   
        flash.now[:alert] = 'Invalid email or password!'
      end
      render :new, status: :unprocessable_entity
    end
  end

  def resend_otp
    @email = params[:email]
    @remember_me  = params[:remember_me]
    user = BusOwner.find_by(email: @email)
    if user
      user.generate_and_send_otp
      flash.now[:notice] = 'OTP resended, check your mail!'
      respond_to do |format|
        format.html {render :otp_verification, status: :ok}
        format.turbo_stream {	flash.now[:notice] = 'OTP resended, check your mail please!.'}
      end
    else
      redirect_to root_path, alert: 'Invalid email address.'
    end
  end

  def create
    @email =  params[:email]
    user = BusOwner.find_by(email: @email)
    remember_me = params[:remember_me]
    if user && user.valid_otp?(params[:otp])
      user.update!(remember_me: remember_me)
      sign_in(:bus_owner, user)
      redirect_to bus_owner_path(user.id), notice: 'Logged in successfully!'
    else
      flash.now[:alert] = 'Invalid email or OTP.'
      respond_to do |format|
        format.html {render :otp_verification, status: :unprocessable_entity}
        format.turbo_stream { render turbo_stream: turbo_stream.update("otp", partial: 
        "bus_owners/sessions/otp_verification",locals: {email: @email, remember_me: @remember_me})}
      end
    end
  end
  
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:otp])
  end

  def after_sign_in_path_for(resource)
    bus_owner_path(resource)
  end
end















  # def otp_verification
  #   sign_out(active_user) if active_user
  #   @email = params[:bus_owner][:email]
  #   if @email.blank?
  #     flash[:alert] = 'Email required!'
  #     redirect_to new_bus_owner_session_path
  #   else 
  #     @user = BusOwner.find_by(email: @email)
  #     @remember_me = params[:bus_owner][:remember_me] 
  #     if @user&.confirmed?
  #       if @user&.valid_password?(params[:bus_owner][:password])
  #         @user.generate_and_send_otp
  #         flash[:notice] = 'A new OTP has been sent to your email.'
  #       else
  #         flash[:alert] = 'Invalid email or password!'
  #         redirect_to new_bus_owner_session_path
  #       end
  #     else 
  #       flash[:alert] = 'You have to confirm your email first!'
  #       redirect_to new_bus_owner_session_path  
  #     end   
  #   end
  # end

app/controllers/bus_owners/unlocks_controller.rb
# frozen_string_literal: true

class BusOwners::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/bus_owners_controller.rb
class BusOwnersController < ApplicationController
  before_action :authenticate_admin_or_bus_owner!, only: [:index, :show]

  def index
    @bus_owners = BusOwner.all
    authorize current_user, policy_class: BusOwnerPolicy
  end

  def show
    @bus_owner = BusOwner.find(params[:id])
    authorize @bus_owner, policy_class: BusOwnerPolicy
  end
end

app/helpers/bus_owners_helper.rb
module BusOwnersHelper
end

app/views/bus_owners/index.html.erb

<div class = "col-md-12 col-xl-12 text-center mt-3 ">
  <div class = "card-block text-center">
    <h2 class = "text-right"><span class="border-bottom">Bus Owner Lists</span></h2>
  </div>
</div>

<div class = "container py-4">
  <div class = "row">
    <div class = "col-lg-12 mx-auto">
      <ul class = "list-group shadow">
        <% @bus_owners.each do |bus_owner| %>
          <li class = "list-group-item">
              <div class = "text-center p-3">
                <h3 class = "mt-0 font-weight-bold mb-2">
                  <%= link_to bus_owner.name, bus_owner %> 
                </h3>
              </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>


app/views/bus_owners/show.html.erb
<%=render "shared/container1"%>

<div class="col-md-4 gradient-custom text-center" style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem; background-color: #F8F8FF; border-right-style:inset">
    <%=image_tag "default_profile_icon.png" ,class:"img-fluid my-5" ,style:"width:80px" %>
    <h5> <%= @bus_owner.name %></h5>
    <p><%= @bus_owner.user_type %></p>
    <%if bus_owner_signed_in?%>
        <h6><%= link_to "My Bookings",bookings_path(@bus_owner.id), class:"btn btn-outline-success mt-2" %></h6> 
    <%end%>
    <%= link_to "Back", :back,class:"btn btn-outline-danger mt-2 mb-2 py-1 px-3" %>
</div>

<div class="col-md-8">
    <div class="card-body p-4">
      <h6> Account Information</h6>
      <hr class="mt-0 mb-2">
      <div class="row pt-0">
        <div class="col-8 mb-0">
          <h6>Email:</h6>
          <p class="text-muted"><%= @bus_owner.email %></p>
        </div>
      </div>

      <div class="row pt-0">
        <div class="col-8 mb-0">
          <h6>Created on:</h6>
          <p class="text-muted"><%= @bus_owner.created_at.localtime.strftime("%d/%m/%Y , %r")%> <%=@bus_owner.created_at.localtime.strftime(" %Z") %> </p>
        </div>
      </div>

      <div class="row pt-0">
        <div class="col-10 mb-0">
          <h6>Registration no:</h6>
          <p class="text-muted"><%= @bus_owner.registration_no %></p>
        </div>
      </div>

      <%if bus_owner_signed_in?%>
        <div class="row pt-1">
          <div class="col-6 mb-3">
            <h6><%= link_to "Update Account" ,edit_bus_owner_registration_path ,class:"btn btn-outline-success mt-2"%> </h6> 
          </div>
        </div>
      <%end%>
     
      <div class="row pt-1">
        <%if bus_owner_signed_in? %>
            <div class="col-6 mb-3">
                <h6><%= link_to "Add new Bus",new_bus_owner_bus_path(@bus_owner),class:"btn btn-outline-success mt-2"%></h6>
            </div> 
        <%end%>
        <div class="col-6 mb-3">
            <h6><%=link_to "Listed Bus",bus_owner_buses_path(@bus_owner),class:"btn btn-outline-success mt-2"%></h6>
        </div> 
      </div> 
    </div> 
</div>
<%=render "shared/container2"%>

