config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root "homes#index"
  get "admin_show/:id", to: "admins#show", as: :admin_show

  devise_scope :user do
    get "/admin_login", to: "users/sessions#new"
    get "/otp_verification", to: "users/confirmations#otp_verification", as: :verify
    patch "/verification", to: "users/sessions#otp_verification", as: :verify_login
    patch "/resend_otp", to: "users/sessions#resend_otp", as: :resend_otp
  end

  devise_scope :bus_owner do
    get "/otp_verification/busowner", to: "bus_owners/confirmations#otp_verification", as: :verify_busowner
    patch "/verification/busowner", to: "bus_owners/sessions#otp_verification", as: :verify_login_busowner
    patch "/resend_otp/busowner", to: "bus_owners/sessions#resend_otp", as: :resend_otp_busowner
  end

  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                       passwords: "users/passwords",
                       confirmations: "users/confirmations",
                     }

  devise_for :bus_owners, class_name: "User", controllers: {
                            registrations: "bus_owners/registrations",
                            sessions: "bus_owners/sessions",
                            passwords: "bus_owners/passwords",
                            confirmations: "bus_owners/confirmations",
                          }

  resources :users, only: [:show, :index]

  resources :bus_owners do
    resources :buses
  end

  resources :buses do
    resources :reservations, only: [:new, :create, :index, :destroy]
  end

  get "/searched_bus", to: "homes#search", as: :search
  get "/bookings/:user_id", to: "reservations#booking", as: :bookings
  get "/get_resv_list/:bus_id", to: "buses#reservations_list", as: :get_resv_list
  patch "approve/:bus_owner_id/:id", to: "admins#approve", as: :approve
  patch "disapprove/:bus_owner_id/:id", to: "admins#disapprove", as: :disapprove

  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/views/admins/approve.turbo_stream.erb
<%= turbo_stream.update @bus do %>
  <span ><%= @bus.approved ? "Approved" : "Not Approved" %></span>
<% end %>

<%= turbo_stream.update  "turbo_buttons_#{@bus.id}" do%>
  <%= link_to "Disapprove", disapprove_path(@busowner.id, @bus.id),  data: {turbo_frame: @bus}, data: {'turbo-method': :patch}, class: "btn btn-outline-danger m-2" %>
<% end %>

<%= turbo_stream.update "book_#{@bus.id}" do%>
    <%= link_to "Book Ticket", new_bus_reservation_path(@bus), class: "btn btn-outline-success  m-2 book", data: {turbo_frame: "_top"} %>
<% end %>

<%= turbo_stream.update "flash", partial: "layouts/flash" %>

app/views/admins/disapprove.turbo_stream.erb
<%= turbo_stream.update @bus do %>
  <span ><%= @bus.approved ? "Approved" : "Not Approved" %></span>
<% end %>

<%= turbo_stream.update  "turbo_buttons_#{@bus.id}"  do%>
  <%= link_to "Approve", approve_path(@busowner.id, @bus.id),  data: {turbo_frame: @bus}, data: {'turbo-method': :patch}, class: "btn btn-outline-success m-2" %>
<% end %>

<%= turbo_stream.update "book_#{@bus.id}" , ""%>

<%= turbo_stream.update "flash", partial: "layouts/flash" %>

app/views/admins/show.html.erb

<%= render "shared/container1" %>
<div class = "col-md-4 gradient-custom text-center" style = "border-top-left-radius: .5rem; border-bottom-left-radius: .5rem; background-color: #F8F8FF; border-right-style:inset">

		<%= image_tag "default_profile_icon.png", class: "img-fluid my-5", style: "width:80px" %>
		<h5> <%= @admin.name %></h5>
		<p><%= @admin.user_type %></p>
		<% if current_user?(@admin) %>
				<h6><%= link_to "My Bookings", bookings_path(@admin.id), class: "btn btn-outline-success mt-2" %></h6> 
		<% end %>
</div>

<div class = "col-md-8">
	<div class = "card-body p-4">
		<h6> Account Information</h6>
		<hr class = "mt-0 mb-2">
		<div class = "row pt-0">
			<div class = "col-8 mb-0">
					<h6>Email:</h6>
					<p class = "text-muted"><%= @admin.email %></p>
			</div>
		</div>
		<div class = "row pt-0">
			<div class = "col-8 mb-0">
				<h6>Created on:</h6>
				<p class = "text-muted"><%= @admin.created_at.localtime.strftime("%d/%m/%Y , %r") %> <%= @admin.created_at.localtime.strftime(" %Z") %> </p>
			</div>
		</div>
		<% if current_user?(@admin) %>
			<div class = "row pt-1">
				<div class = "col-6 mb-3">
					<h6><%= link_to "Bus Owner List", bus_owners_path, class: "btn btn-outline-success mt-2" %></h6>
				</div>
				<div class = "col-6 mb-3">
					<h6><%= link_to "Update Account", edit_user_registration_path, class: "btn btn-outline-success mt-2" %> </h6> 
				</div>
			</div>
		<% end %>
	</div>
</div>
<%= render "shared/container2" %>