config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root "homes#index"
  get "admin_show/:id", to: "admins#show", as: :admin_show

  devise_scope :user do
    get "/admin_login", to: "users/sessions#new"
    get "/otp_verification", to: "users/confirmations#otp_verification", as: :verify
    patch "/verification", to: "users/sessions#otp_verification", as: :verify_login
    patch "/resend_otp", to: "users/sessions#resend_otp", as: :resend_otp
  end

  devise_scope :bus_owner do
    get "/otp_verification/busowner", to: "bus_owners/confirmations#otp_verification", as: :verify_busowner
    patch "/verification/busowner", to: "bus_owners/sessions#otp_verification", as: :verify_login_busowner
    patch "/resend_otp/busowner", to: "bus_owners/sessions#resend_otp", as: :resend_otp_busowner
  end

  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                       passwords: "users/passwords",
                       confirmations: "users/confirmations",
                     }

  devise_for :bus_owners, class_name: "User", controllers: {
                            registrations: "bus_owners/registrations",
                            sessions: "bus_owners/sessions",
                            passwords: "bus_owners/passwords",
                            confirmations: "bus_owners/confirmations",
                          }

  resources :users, only: [:show, :index]

  resources :bus_owners do
    resources :buses
  end

  resources :buses do
    resources :reservations, only: [:new, :create, :index, :destroy]
  end

  get "/searched_bus", to: "homes#search", as: :search
  get "/bookings/:user_id", to: "reservations#booking", as: :bookings
  get "/get_resv_list/:bus_id", to: "buses#reservations_list", as: :get_resv_list
  patch "approve/:bus_owner_id/:id", to: "admins#approve", as: :approve
  patch "disapprove/:bus_owner_id/:id", to: "admins#disapprove", as: :disapprove

  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/views/shared/_container1.html.erb
<section>
  <div class = "container py-5">
    <div class = "row d-flex justify-content-center align-items-center h-100">
      <div class = "col col-lg-6 mb-4 mb-lg-0">
        <div class = "card mb-3 shadow" style = "border-radius: .5rem;">
          <div class = "row g-0">
                    

                    

app/views/shared/_container2.html.erb
</div>
</div>
</div>
</div>
</div>
</section>

app/views/shared/_edit.html.erb

<%= render "shared/errors", object: resource %>
<section>
	<div class = "container py-4 ">
		<div class = "row d-flex justify-content-center align-items-center">
			<div class = "col col-xl-8">
				<div class = "card shadow" style = "border-radius: 1rem;">
					<div class = "row g-0 pb-3">
						<div class = "col-md-6 col-lg-5 d-none d-md-block text-center">
							<%= image_tag "update.png", class: "img-fluid", style: "border-radius:10px"%>
							<%= button_to "Delete Account", registration_path(resource_name), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class: "btn btn-outline-danger btn-mg" %>
						</div>
						<div class = "col-md-6 col-mg-7 d-flex align-items-center">
								<div class = "card-body p-2 p-mg-5 text-black">
									<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
										<div class = "d-flex align-items-center mb-2 pb-1">
											<span class = "h1 fw-bold mb-0">
												<%= image_tag "bus_logo2.png", class: "form_img" %> 
											</span>
											<span class = "h2 fw-bold mb-0"> Update account</span>
										</div>
										<div class = "form-outline mb-2">
											<%=  f.text_field :name, placeholder: "Enter name", required: "",
											autofocus: true, class: "form-control form-control-mg" %>
										</div>
										<div class = "form-outline mb-3">
											<%=  f.email_field :email, placeholder: "Enter email", required: "",autofocus: true, class: "form-control form-control-mg" %>
											<% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
												<div>Currently waiting confirmation for: 
													<%= resource.unconfirmed_email %>
												</div>
											<% end %>
										</div>
										<div class = "form-outline mb-3">
											<%= f.password_field :password, placeholder: "Password",
											class: "form-control form-control-mg", autocomplete: "new-password" %>   
											<% if @minimum_password_length %>
												<em>(<%= @minimum_password_length %> characters minimum)</em>
											<% end %><br />
										</div>
										<div class = "form-outline mb-3">
											<%=  f.password_field :password_confirmation, placeholder: "Confirm password", class: "form-control form-control-mg", autocomplete: "new-password"%>        
										</div>
										<div class = "form-outline mb-3">
											<i>(we need your current password to confirm your changes)</i><br />
											<%= f.password_field :current_password, autocomplete: "current-password",class: "form-control form-control-mg", placeholder: "current password" %>
										</div>
										<% if resource.bus_owner? %>
											<div class = "form-outline mb-3">
												<%=  f.text_field :registration_no, placeholder: "Registration no" ,required: "", class: "form-control form-control-mg" %>        
											</div>
										<% end %>
										<div class = "pt-1 mb-1">
											<%= f.submit "Update Account", class: "btn btn-outline-success btn-mg" %>
										</div>
									<% end %>
								</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/shared/_edit_password.html.erb

<%= render "shared/errors", object: resource %>
<% unless signed_in? %>
	<section>
		<div class = "container py-5">
			<div class = "row d-flex justify-content-center align-items-center">
				<div class = "col col-xl-8">
					<div class = "card shadow" style = "border-radius: 1rem;">
						<div class = "row g-0">
							<div class = "col-md-4 col-lg-5 d-none d-md-block">
								<%= image_tag "forget_password.png", class: "img-fluid", style: "border-radius:10px" %>
							</div>
							<div class = "col-md-6 col-lg-7 d-flex align-items-center">
								<div class = "card-body pt-1 p-md-3 text-black">
									<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :put }) do | f | %>

										<%= f.hidden_field :reset_password_token %>
										<div class = "d-flex align-items-center mb-3 pb-1">
											<span class = "h1 fw-bold mb-0">
												<%= image_tag "bus_logo2.png", class: "form_img" %> 
											</span>
											<span class = "h2 fw-bold mb-0"> Change Password</span>
										</div>

										<div class = "form-outline mb-2 pb-2">
											<% if @minimum_password_length %>
												<em>(<%= @minimum_password_length %> characters minimum)</em><br />
											<% end %>
											<%= f.password_field :password, autofocus: true, autocomplete: "new-password",class: "form-control form-control-mg", placeholder: "Enter new password" %>
										</div>
										<div class = "form-outline mb-2 pb-2">
											<%= f.password_field :password_confirmation, autofocus: true, autocomplete: "new-password",class: "form-control form-control-mg", placeholder: "Confirm new password" %>
										</div>

										<div class = "pt-1 mb-3">
											<%= f.submit "Change password ", class: "btn btn-outline-success btn-mg btn-block" %>
										</div>
								
										<p class = "mb-0 pb-lg-1 text-muted" style = 'color: #393f81;'>
											User login | <%= link_to "Login here", new_user_session_path %>
											<br>
											User signup | <%= link_to "Click here", new_user_registration_path %>
											<br>
											Bus owner login | <%= link_to "Login here", new_bus_owner_session_path %> 
											<br>
											Bus owner signup | <%= link_to "Click here", new_bus_owner_registration_path %>
										</p>
										
										<a href = "#!" class = "small text-muted">Terms of use</a>
										<a href = "#!" class = "small text-muted"> | Privacy policy</a>        
									<% end %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
<% end %>

app/views/shared/_errors.html.erb
<% unless object == nil %>
	<% if object.errors.any? %>
		<section class = "errors flash__message bg-danger">
			<h6 class = "m-0 p-0">Please correct the following <%= pluralize(object.errors.size, "error") %>:</h6>
			<ul class = "m-0 p-0" >
				<% object.errors.full_messages.each do | message | %>
						<li class = "m-0 p-0"><%= message %></li>
				<% end %>
			</ul>
		</section>
	<% end %>
<% end %>

app/views/shared/_new.html.erb

<%= render "shared/errors", object: resource %>
<section>
	<div class = "container py-4">
		<div class = "row d-flex justify-content-center align-items-center">
			<div class = "col col-xl-8">
				<div class = "card shadow" style = "border-radius: 1rem;">
					<div class = "row g-0">
						<div class = "col-md-6 col-lg-5 d-none d-md-block">
							<%= image_tag "usersignup.jpg", class: "img-fluid", style: "border-radius:10px" %>
						</div>
						<div class = "col-md-6 col-mg-7 d-flex align-items-center">
							<div class = "card-body p-2 p-mg-5 text-black">
								<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
									<div class = "d-flex align-items-center mb-2 pb-0">
										<span class = "h1 fw-bold mb-0">
											<%= image_tag "bus_logo2.png", class: "form_img" %> 
										</span>
										<span class = "h2 fw-bold mb-0"> Signup</span>
									</div>
                  <% if @type == "bus_owner" %>
									  <h5 class = "fw-normal mb-1 pb-0" style = "letter-spacing: 1px;">Create a bus owner account</h5>
                  <% else %>
                    <h5 class = "fw-normal mb-1 pb-0" style = "letter-spacing: 1px;">Create an account</h5>
                  <% end %>
									<div class = "form-outline mb-2">
										<%= f.text_field :name, placeholder: "Enter name", required: "", autofocus: true, class: "form-control form-control-mg" %>
									</div>
									<div class = "form-outline mb-3">
										<%= f.email_field :email, placeholder: "Enter email", required: "", autofocus:true, class: "form-control form-control-mg" %>
									</div>
									<div class = "form-outline mb-1">
										<%= f.password_field :password, placeholder: "Password", class: "form-control form-control-mg", autocomplete: "new-password" %>   
										<% if @minimum_password_length %>
											<em>(<%= @minimum_password_length %> characters minimum)</em>
										<% end %><br />
									</div>
									<div class = "form-outline mb-2">
										<%= f.password_field :password_confirmation, placeholder: "Confirm password", class: "form-control form-control-mg", autocomplete: "new-password" %>        
									</div>
									<% if @type == "bus_owner" %>
                    <div class = "form-outline mb-1">
                      <%= f.text_field :registration_no, placeholder: "Registration no", required: "", class: "form-control form-control-mg" %>        
                    </div>
									<% end %>
									<div class = "pt-1 mb-1">
										<%= f.submit "Sign Up", class: "btn btn-dark btn-mg btn-block" %>
									</div>
                  <% if @type == "bus_owner" %>
									  <%= render "bus_owners/shared/links" %>  
                  <% else %> 
                    <%= render "users/shared/links" %>
								  <% end %>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/shared/_new_password.html.erb
<%= render "shared/errors", object: resource %>
<% unless signed_in? %>
	<section>
		<div class = "container py-5 ">
			<div class = "row d-flex justify-content-center align-items-center ">
				<div class = "col col-xl-8">
					<div class = "card shadow" style = "border-radius: 1rem;">
						<div class = "row g-0">
							<div class = "col-md-4 col-lg-5 d-none d-md-block">
								<%= image_tag "forget_password.png", class: "img-fluid", style: "border-radius:10px" %>
							</div>
							<div class = "col-md-6 col-lg-7 d-flex align-items-center">
								<div class = "card-body pt-1 p-md-3 text-black">
									<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do | f | %>

										<div class = "d-flex align-items-center mb-3 pb-1">
											<span class = "h1 fw-bold mb-0">
												<%= image_tag "bus_logo2.png", class: "form_img" %>
											</span>
											<span class = "h2 fw-bold mb-0"> Forgot Password</span>
										</div>
										<div class = "form-outline mb-2 pb-2">
											<%= f.email_field :email, placeholder: "Enter Email", required: "", autofocus: true, class: "form-control form-control-mg" %>
										</div>
										
										<div class = "pt-1 mb-3">
											<%= f.submit "Reset password", class: "btn btn-outline-success btn-mg btn-block" %>
										</div>
								
										<p class = "mb-0 pb-lg-1 text-muted" style = 'color: #393f81;'>
											User login | <%= link_to "Login here", new_user_session_path %>
											<br>
											User signup | <%= link_to "Click here", new_user_registration_path %>
											<br>
											Bus owner login | <%= link_to "Login here", new_bus_owner_session_path %> 
											<br>
											Bus owner signup | <%= link_to "Click here", new_bus_owner_registration_path %>
										</p>
										
										<a href = "#!" class = "small text-muted">Terms of use </a>
										<a href = "#!" class = "small text-muted"> | Privacy policy</a>        
									<% end %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
<% end %>