config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root "homes#index"
  get "admin_show/:id", to: "admins#show", as: :admin_show

  devise_scope :user do
    get "/admin_login", to: "users/sessions#new"
    get "/otp_verification", to: "users/confirmations#otp_verification", as: :verify
    patch "/verification", to: "users/sessions#otp_verification", as: :verify_login
    patch "/resend_otp", to: "users/sessions#resend_otp", as: :resend_otp
  end

  devise_scope :bus_owner do
    get "/otp_verification/busowner", to: "bus_owners/confirmations#otp_verification", as: :verify_busowner
    patch "/verification/busowner", to: "bus_owners/sessions#otp_verification", as: :verify_login_busowner
    patch "/resend_otp/busowner", to: "bus_owners/sessions#resend_otp", as: :resend_otp_busowner
  end

  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                       passwords: "users/passwords",
                       confirmations: "users/confirmations",
                     }

  devise_for :bus_owners, class_name: "User", controllers: {
                            registrations: "bus_owners/registrations",
                            sessions: "bus_owners/sessions",
                            passwords: "bus_owners/passwords",
                            confirmations: "bus_owners/confirmations",
                          }

  resources :users, only: [:show, :index]

  resources :bus_owners do
    resources :buses
  end

  resources :buses do
    resources :reservations, only: [:new, :create, :index, :destroy]
  end

  get "/searched_bus", to: "homes#search", as: :search
  get "/bookings/:user_id", to: "reservations#booking", as: :bookings
  get "/get_resv_list/:bus_id", to: "buses#reservations_list", as: :get_resv_list
  patch "approve/:bus_owner_id/:id", to: "admins#approve", as: :approve
  patch "disapprove/:bus_owner_id/:id", to: "admins#disapprove", as: :disapprove

  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :authenticate_bus_owner!, only: [:new, :edit, :update, :destroy]
  before_action :authenticate_admin_or_bus_owner!, only: [:index]
  before_action :authorize_bus_owner, only: [:edit, :update, :destroy, :index]

  def reservations_list
    @date = params[:date]
    @bus = Bus.find(params[:bus_id])
    @reservations = @bus.reservations.where(date: @date)
    authorize @bus
  end

  def new
    @busowner = BusOwner.find(params[:bus_owner_id])
    @bus = @busowner.buses.new
  end

  def show
    @busowner = BusOwner.find(params[:bus_owner_id])
    @bus = @busowner.buses.find(params[:id])
    @available_seats = @bus.seats
  end

  def create
    @busowner = BusOwner.find(params[:bus_owner_id])
    @bus = @busowner.buses.new(bus_params)
    if @bus.save
      redirect_to bus_owner_path(@busowner),
                  notice: "Bus added successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @buses = @busowner.buses.all
  end

  def edit
    @bus = @busowner.buses.find(params[:id])
  end

  def update
    @bus = @busowner.buses.find(params[:id])
    if @bus.update(bus_params)
      redirect_to bus_owner_bus_path(@busowner, @bus),
                  notice: "Bus info. updated successfully!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bus = @busowner.buses.find(params[:id])
    @bus.destroy
    redirect_to bus_owner_buses_path(@busowner),
                status: :see_other, notice: "Bus removed successfully!"
  end

  private

  def bus_params
    params.require(:bus).permit(:name, :registration_no, :route, :total_seat, :approved, :main_image)
  end

  def authorize_bus_owner
    @busowner = BusOwner.find_by(id: params[:bus_owner_id])
    authorize @busowner, policy_class: BusPolicy
  end
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/_form.html.erb

<section>
	<div class = "container py-5">
		<div class = "row d-flex justify-content-center align-items-center">
			<div class = "col col-xl-10">
				<div class = "card shadow" style = "border-radius: 1rem;">
					<div class = "row g-0">
						<div class = "col-md-6 col-lg-5 d-none d-md-block mt-4 pt-4">
							<% if object2.main_image.attached? %>
								<%= image_tag object2.main_image, class: "img-fluid", style: "border-radius:10px" %>
							<% else %>
								<%= image_tag "bus_logo2.png", class: "img-fluid" %>
							<% end %>
						</div>
						<div class = "col-md-6 col-mg-7 d-flex align-items-center">
							<div class = "card-body p-2 p-mg-5 text-black">
								<%= form_with(model: [object1,object2])   do |f| %> 
									<div class = "d-flex align-items-center mb-2 pb-1">
										<span class = "h1 fw-bold mb-0">
											<%= image_tag "bus_logo2.png", class: "form_img" %> 
										</span>
										<% unless object2.persisted? %>
											<span class = "h2 fw-bold mb-0">Add Bus</span>
										<% else %>
											<span class = "h2 fw-bold mb-0">Update Bus</span>
										<% end %>
									</div>
									<% unless object2.persisted? %>
										<h5 class = "fw-normal mb-2 pb-2" style = "letter-spacing: 1px;">Enter Bus inforation</h5>
									<% end %>
									<div class = "form-outline mb-3">
										<%= f.text_field :name, placeholder: "Enter bus name", required: "", autofocus: true, class: "form-control form-control-mg" %>
									</div>
									<div class = "form-outline mb-3">
										<%=  f.text_field :registration_no, placeholder: "Enter registration no", required: "", autofocus: true, class: "form-control form-control-mg" %>
									</div>
									<div class = "form-outline mb-3">
										<%= f.text_field :route, placeholder: "Route", class: "form-control form-control-mg" %>        
									</div>
									<div class = "form-outline mb-3">
										<%= f.text_field :total_seat, placeholder: "Total no of seats", class: "form-control form-control-mg" %>        
									</div>
									<div class = "form-outline mb-3">
										<%= f.label :main_image, "Upload bus image", class: "mb-1 pb-lg-2" %>
										<%= f.file_field :main_image, placeholder: "Upload image", class: "form-control form-control-mg" %>        
									</div>
									<% unless object2.persisted? %>
										<div class = "pt-1 mb-1">
											<%= f.submit "Add Bus", class: "btn btn-dark btn-mg btn-block" %>
										</div>
									<% else %>
										<div class = "pt-1 mb-1">
											<%= f.submit "Update Bus", class: "btn btn-dark btn-mg btn-block" %>
										</div>
									<% end %> 
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/buses/edit.html.erb
<%= render "shared/errors", object: @bus %>
<%= render "form", object1: @busowner, object2: @bus %> 

app/views/buses/index.html.erb
<% if current_user_admin? %>
  <div class = "col-md-12 col-xl-12 text-center mt-3">
    <div class = "card-block text-center">
      <h2 class = "text-right"><span class = "border-bottom">Bus Listed By <%= @busowner.name %></span></h2>
    </div>
  </div>
<% end %>

<div class = "container py-4">
  <div class = "row">
    <div class = "col-lg-12 mx-auto">
      <ul class = "list-group shadow">
        <% @buses .each do | bus | %>
          <li class = "list-group-item">
            <div class = "media align-items-lg-center flex-column flex-lg-row p-2">
              <div class = "row">
                <div class = "col-lg-8 mx-auto mt-3">
                  <div class = "media-body order-2 order-lg-1">
                    <h3 class= "mt-0 font-weight-bold mb-2">
                      <%= link_to bus.name, bus_owner_bus_path(@busowner.id, bus.id),  data:    {turbo_frame: "_top"} %>
                    </h3>
                      Status:
                      <%= turbo_frame_tag bus do %>
										    <span ><%= bus.approved ? "Approved" : "Not Approved" %></span>
								      <% end %>
                 
                    <% if current_user_admin? %>
								      <%= turbo_frame_tag "turbo_buttons_#{bus.id}" do %>
									      <% if bus.approved? %>
										      <%= link_to "Disapprove", disapprove_path(@busowner.id,bus.id),  data:    {turbo_frame: bus} , data: {'turbo-method': :patch}, class: "btn btn-outline-danger m-2" %>
									      <% else %>
										      <%= link_to "Approve", approve_path(@busowner.id,bus.id), data:     {turbo_frame: bus},data: {'turbo-method': :patch},  class: "btn btn-outline-success m-2" %>
									      <% end %>
								      <% end %>
							      <% end %>
                    <%= turbo_frame_tag "book_#{bus.id}" do %>
								      <% if bus.approved? %>
									      <%= link_to "Book Ticket", new_bus_reservation_path(bus.id), class: "btn btn-outline-success  m-2 book" ,data: {turbo_frame: "_top"}  %>
								      <% end %>
							      <% end %>
                  </div>
                </div>
                <div class="col-lg-2 mx-auto">
                  <% if bus.main_image.attached? %>
                    <%= image_tag bus.main_image, class: "ml-lg-5 img-fluid" %>
                  <% else %>
                    <%= image_tag "bus_logo2.png", class: "ml-lg-5 img-fluid m-0 p-0" %>
                  <% end %>
                </div>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>


app/views/buses/new.html.erb
<%= render "shared/errors", object: @bus %>

<%= render "form", object1: @busowner, object2: @bus%> 

app/views/buses/reservations_list.html.erb

<% # USED BY BUS OWNER %>

<div class = "container mt-5">
  <div class = "row justify-content-center">
    <div class = "col-md-6">
      <div class = "card">
        <div class = "card-body text-center">
					<%= form_with(url: :get_resv_list, method: :get) do |f| %>
						<h5 class = "card-title"><%= f.label :date, "Please select Date ", class: "date_label text-decoration-underline mb-1" %></h5>
						<div id = "datepicker" class = "input-group date col-md-6" data-date-format = "mm-dd-yyyy">
								<%= f.date_field :date, value: @date, class: "datepicker form-control text-center", required: "" %>
						</div>
						<%= f.hidden_field :bus_id, value: @bus.id %>
						<%= f.submit "See reservations", class: "btn btn-outline-success  mt-1", data: { turbo_frame: "lists" } %>
					<% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= turbo_frame_tag "lists" do %>
	<% unless @reservations.empty? %>
		<div class = "container mt-4">
			<div class = "row flex justify-content-center m-4 shadow" style = "border-radius:10px;">
				<div class = "card-header bg-black  text-center py-2 mb-3 xx" style = "color: #ff0000;">
						<h6> Reservations for : <%= @bus.name %> on <%= @date %>  </h6>
				</div>
				<% @reservations.each do |r| %>
					<div class = "col-md-4 mb-4  mt-3">
						<div class = "card" style = "border: 1px solid #ced4da; border-radius: 8px;">
							<div class = "card-header xx bg-black text-center py-2" style = " color: #00ff00;">
								<h6>Ticket ID: <%= r.id %> </h6>
							</div>
							<div class = "card-body">
								<p class = "card-text m-0"> <strong>Seat ID:</strong> <%= r.seat_id %></p>
								<p class = "card-text m-0"> <strong>Seat No:</strong> <%= r.seat.seat_no %></p>
								<p class = "card-text m-0"> <strong>Passenger ID:</strong> <%= r.user.id %></p>
								<p class = "card-text m-0"> <strong>Passenger Name:</strong> <%= r.user.name %></p>
							</div>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	<% end %>
<% end %>










app/views/buses/show.html.erb
<section>
	<div class = "container py-5">
		<div class = "row justify-content-center">
			<div class = "col-md-8 col-lg-8 col-xl-8">
				<div class = "card text-black shadow">
					<div class = "text-center">
						<% if @bus.main_image.attached? %>
							<%= image_tag @bus.main_image, class: "card-img-top", style: "width:350px" %>
						<% else %>
							<%= image_tag "bus_logo2.png", class: "card-img-top", style: "width:200px" %>
						<% end %>
					</div>
					<div class = "card-body pt-0 mt-0">
						<div class = "text-center">
							<h4 class = "card-title">Bus name : <%= @bus.name %></h4>
							<p class = "text-muted mb-2">Owner : <%= @busowner.name %></p>
						</div>
					<div>
					<div class = "d-flex justify-content-between">
						<span>Total number of seats: </span><span><%= @bus.total_seat %></span>
					</div>
					<div class = "d-flex justify-content-between">
						<span>Registration no: </span><span><%= @bus.registration_no %></span>
					</div>
					<div class = "d-flex justify-content-between">
						<span>Route:</span><span><%= @bus.route %></span>
					</div>
					<% if current_user_admin? || bus_owner_signed_in? %>
							<div class = "d-flex justify-content-between">
								<span>Status:</span>
								<%= turbo_frame_tag @bus do %>
										<span ><%= @bus.approved ? "Approved" : "Not Approved" %></span>
								<% end %>
							</div>
					<% end %>
					<div class = "row">
						<div class = "d-flex flex-column flex-sm-row justify-content-evenly">

							<% if policy(@bus).view? %>
								<%= link_to "Update Bus", edit_bus_owner_bus_path(@busowner, @bus), class: "btn btn-outline-success m-2" %>
								<%= button_to "Remove Bus", bus_owner_bus_path(@busowner, @bus), method: :delete, class: "btn btn-outline-danger  m-2", style: 'width: 95%;' %>
								<%= link_to "Reservations List", get_resv_list_path(@bus), class: "btn btn-outline-success m-2" %>
							<% end %>
							
							<%= turbo_frame_tag "book_#{@bus.id}" do %>
								<% if @bus.approved? %>
									<%= link_to "Book Ticket", new_bus_reservation_path(@bus.id), class: "btn btn-outline-success  m-2 book", data: {turbo_frame: "_top"}%>
								<% end %>
							<% end %>

							<% if current_user_admin? %>
								<%= turbo_frame_tag "turbo_buttons_#{@bus.id}" do %>
									<% if @bus.approved? %>
										<%= link_to "Disapprove", disapprove_path(@busowner.id,@bus.id),  data:   {turbo_frame: "bus_#{@bus.id}"} , data: {'turbo-method': :patch}, class: "btn btn-outline-danger m-2" %>
									<% else %>
										<%= link_to "Approve", approve_path(@busowner.id,@bus.id), data:     {turbo_frame: "bus_#{@bus.id}"},data: {'turbo-method': :patch},  class: "btn btn-outline-success m-2" %>
									<% end %>
								<% end %>
							<% end %>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>